// SPDX-License-Identifier: MPL-2.0
// SPDX-FileCopyrightText: 2026 Aryan Ameri <info@ameri.me>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

/**
 * Complete Caddyfile generation.
 */

import type { CaddyfileConfig } from "../schema";
import { createBuilder } from "./format";
import { generateGlobalOptions, hasGlobalOptions } from "./global";
import { generateSites } from "./sites";
import { generateSnippets } from "./snippets";

/**
 * Generate a complete Caddyfile from configuration.
 */
export const generateCaddyfile = (config: CaddyfileConfig): string => {
  const builder = createBuilder();

  // Header comment
  builder.comment("Caddyfile generated by divban");
  builder.comment(`Generated at: ${new Date().toISOString()}`);
  builder.comment("DO NOT EDIT MANUALLY");
  builder.blank();

  // Global options (if any)
  if (config.global && hasGlobalOptions(config.global)) {
    builder.comment("Global options");
    builder.raw(generateGlobalOptions(config.global).trim());
    builder.blank();
  }

  // Snippets (if any)
  if (config.snippets && config.snippets.length > 0) {
    builder.comment("Snippets");
    builder.raw(generateSnippets(config.snippets).trim());
    builder.blank();
  }

  // Sites
  builder.comment("Sites");
  builder.raw(generateSites(config.sites).trim());

  return builder.build();
};

// Re-export all sub-modules
export * from "./format";
export * from "./global";
export * from "./snippets";
export * from "./matchers";
export * from "./directives";
export * from "./sites";
