// SPDX-License-Identifier: MPL-2.0
// SPDX-FileCopyrightText: 2026 Aryan Ameri <info@ameri.me>
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

/**
 * Complete Caddyfile generation.
 */

import { Option, pipe } from "effect";
import { nonEmpty } from "../../../lib/option-helpers";
import type { CaddyfileConfig } from "../schema";
import { Caddy, type CaddyOp, caddyfile } from "./format";
import { globalOps, hasGlobalOptions } from "./global";
import { sitesOps } from "./sites";
import { snippetsOps } from "./snippets";

/**
 * Generate a complete Caddyfile from configuration.
 * Composes operations from each module.
 */
export const generateCaddyfile = (config: CaddyfileConfig): string => {
  const globalOpt = pipe(Option.fromNullable(config.global), Option.filter(hasGlobalOptions));
  const snippetsOpt = nonEmpty(config.snippets);

  return caddyfile(
    // Header comment
    Caddy.comment("Caddyfile generated by divban"),
    Caddy.comment(`Generated at: ${new Date().toISOString()}`),
    Caddy.comment("DO NOT EDIT MANUALLY"),
    Caddy.blank,

    // Global options - use Option.match for exhaustive handling
    pipe(
      globalOpt,
      Option.match({
        onNone: (): CaddyOp => Caddy.id,
        onSome: (global): CaddyOp =>
          Caddy.seq(Caddy.comment("Global options"), globalOps(global), Caddy.blank),
      })
    ),

    // Snippets
    pipe(
      snippetsOpt,
      Option.match({
        onNone: (): CaddyOp => Caddy.id,
        onSome: (snippets): CaddyOp =>
          Caddy.seq(Caddy.comment("Snippets"), snippetsOps(snippets), Caddy.blank),
      })
    ),

    // Sites (always present)
    Caddy.comment("Sites"),
    sitesOps(config.sites)
  );
};

// Re-export all sub-modules

// format.ts - CaddyOp DSL and utilities
export {
  escapeValue,
  indent,
  joinArgs,
  openBlock,
  formatLine,
  Caddy,
  caddyfile,
  type CaddyOp,
} from "./format";

// global.ts
export { generateGlobalOptions, globalOps, hasGlobalOptions } from "./global";

// snippets.ts
export {
  generateSnippet,
  generateSnippets,
  snippetOps,
  snippetsOps,
  importSnippet,
} from "./snippets";

// matchers.ts
export {
  generateNamedMatcher,
  generateNamedMatchers,
  matcherOps,
  matchersOps,
  matcherRef,
  isEmptyMatcher,
} from "./matchers";

// directives.ts
export {
  renderDirective,
  renderDirectives,
  directiveOp,
  directivesOps,
  Directives,
} from "./directives";

// sites.ts
export {
  generateRoute,
  generateSite,
  generateSites,
  routeOps,
  siteOps,
  sitesOps,
  Sites,
} from "./sites";
