/**
 * Environment file generation for multi-container stacks.
 * Generates grouped environment files with comments.
 */

/**
 * Environment variable group.
 */
export interface EnvGroup {
  /** Group name (used in comment) */
  name: string;
  /** Environment variables */
  vars: Record<string, string | number | boolean | undefined>;
}

/**
 * Environment file configuration.
 */
export interface EnvFileConfig {
  /** Header comment */
  header?: string;
  /** Variable groups */
  groups: EnvGroup[];
}

/**
 * Escape a value for environment file format.
 */
export const escapeEnvValue = (value: string): string => {
  // If value contains special characters, quote it
  if (
    value.includes(" ") ||
    value.includes('"') ||
    value.includes("'") ||
    value.includes("$") ||
    value.includes("`") ||
    value.includes("\\") ||
    value.includes("\n")
  ) {
    // Use double quotes and escape
    const escaped = value
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\$/g, "\\$")
      .replace(/`/g, "\\`")
      .replace(/\n/g, "\\n");
    return `"${escaped}"`;
  }
  return value;
};

/**
 * Format a single environment variable line.
 */
export const formatEnvLine = (key: string, value: string | number | boolean): string => {
  const stringValue = typeof value === "boolean" ? (value ? "true" : "false") : String(value);
  return `${key}=${escapeEnvValue(stringValue)}`;
};

/**
 * Generate an environment file with grouped variables.
 */
export const generateEnvFile = (config: EnvFileConfig): string => {
  const lines: string[] = [];

  // Header
  if (config.header) {
    lines.push(`# ${config.header}`);
    lines.push(`# Generated by divban - DO NOT EDIT MANUALLY`);
    lines.push(`# Generated at: ${new Date().toISOString()}`);
    lines.push("");
  }

  // Groups
  for (const group of config.groups) {
    // Skip empty groups
    const entries = Object.entries(group.vars).filter(([_, v]) => v !== undefined);
    if (entries.length === 0) continue;

    // Group comment
    lines.push(`# ${group.name}`);
    lines.push(`# ${"─".repeat(40)}`);

    // Variables
    for (const [key, value] of entries) {
      if (value !== undefined) {
        lines.push(formatEnvLine(key, value));
      }
    }

    lines.push("");
  }

  return lines.join("\n");
};

/**
 * Generate an environment file from a flat record.
 */
export const generateSimpleEnvFile = (
  vars: Record<string, string | number | boolean | undefined>,
  header?: string
): string => {
  return generateEnvFile({
    header,
    groups: [{ name: "Environment Variables", vars }],
  });
};

/**
 * Parse an environment file into a record.
 */
export const parseEnvFile = (content: string): Record<string, string> => {
  const vars: Record<string, string> = {};

  for (const line of content.split("\n")) {
    const trimmed = line.trim();

    // Skip empty lines and comments
    if (!trimmed || trimmed.startsWith("#")) continue;

    // Find first = sign
    const eqIndex = trimmed.indexOf("=");
    if (eqIndex === -1) continue;

    const key = trimmed.slice(0, eqIndex);
    let value = trimmed.slice(eqIndex + 1);

    // Remove quotes if present
    if ((value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }

    // Unescape
    value = value
      .replace(/\\n/g, "\n")
      .replace(/\\"/g, '"')
      .replace(/\\\$/g, "$")
      .replace(/\\`/g, "`")
      .replace(/\\\\/g, "\\");

    vars[key] = value;
  }

  return vars;
};

/**
 * Merge multiple environment records.
 */
export const mergeEnv = (
  ...envs: (Record<string, string | number | boolean | undefined> | undefined)[]
): Record<string, string> => {
  const result: Record<string, string> = {};

  for (const env of envs) {
    if (!env) continue;
    for (const [key, value] of Object.entries(env)) {
      if (value !== undefined) {
        result[key] = typeof value === "boolean" ? (value ? "true" : "false") : String(value);
      }
    }
  }

  return result;
};

/**
 * Create common environment groups.
 */
export const CommonEnvGroups = {
  /** Database connection */
  database: (config: {
    host?: string;
    port?: number;
    name?: string;
    user?: string;
    password?: string;
  }): EnvGroup => ({
    name: "Database Configuration",
    vars: {
      DB_HOST: config.host,
      DB_PORT: config.port,
      DB_NAME: config.name,
      DB_USERNAME: config.user,
      DB_PASSWORD: config.password,
    },
  }),

  /** Redis connection */
  redis: (config: { host?: string; port?: number; password?: string }): EnvGroup => ({
    name: "Redis Configuration",
    vars: {
      REDIS_HOST: config.host,
      REDIS_PORT: config.port,
      REDIS_PASSWORD: config.password,
    },
  }),

  /** Basic server config */
  server: (config: { host?: string; port?: number; publicUrl?: string }): EnvGroup => ({
    name: "Server Configuration",
    vars: {
      HOST: config.host,
      PORT: config.port,
      PUBLIC_URL: config.publicUrl,
    },
  }),
};
